services:
  db:
    image: postgis/postgis:16-3.4
    container_name: aq_postgis
    environment:
      POSTGRES_USER: aq
      POSTGRES_PASSWORD: aq
      POSTGRES_DB: aqdb
    ports:
      - "5432:5432"
    volumes:
      - aq_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aq -d aqdb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  aq_pgdata:
